version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - default

  postgres-user:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wassimos
      POSTGRES_DB: systemreservationdb  # All services use this one DB
    ports:
      - "5432:5432"
    networks:
      - default

  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    depends_on:
      - postgres-user
    networks:
      - default
    entrypoint: ["bash", "/wait-for-postgres.sh", "postgres-user", "5432", "python", "app.py"]  # Use bash for script execution

  salle-service:
    build: ./salle-service
    ports:
      - "5002:5002"
    depends_on:
      - postgres-user  # Same DB for all services
    networks:
      - default
    entrypoint: ["bash", "/wait-for-postgres.sh", "postgres-user", "5432", "python", "app.py"]  # Use bash for script execution

  reservation-service:
    build: ./reservation-service
    ports:
      - "5003:5003"
    depends_on:
      - postgres-user  # Same DB for all services
      - kafka
    networks:
      - default
    entrypoint: ["bash", "/wait-for-postgres.sh", "postgres-user", "5432", "python", "app.py"]  # Use bash for script execution

networks:
  default:
    name: room-network

