name: CI/CD - Build and Push to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push user-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./user-service
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service

    - name: Build and push salle-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/salle-service ./salle-service
        docker push ${{ secrets.DOCKER_USERNAME }}/salle-service

    - name: Build and push reservation-service
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/reservation-service ./reservation-service
        docker push ${{ secrets.DOCKER_USERNAME }}/reservation-service
